Traceback (most recent call last):
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/runner/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
@qml.template
def var_layer(x):
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)

    qml.U1(x[0], wires=0)
    qml.U1(x[1], wires=1)

    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)

    qml.CNOT(wires=[0, 1])
    qml.U1(np.pi * np.cos(x[0]) * np.cos(x[1]), wires=1)
    qml.CNOT(wires=[0, 1])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_2255/2703634271.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;34m@[0m[0mqml[0m[0;34m.[0m[0mtemplate[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mdef[0m [0mvar_layer[0m[0;34m([0m[0mx[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mqml[0m[0;34m.[0m[0mHadamard[0m[0;34m([0m[0mwires[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mqml[0m[0;34m.[0m[0mHadamard[0m[0;34m([0m[0mwires[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m~/work/qmlcourse/qmlcourse/.venv/lib/python3.8/site-packages/pennylane/__init__.py[0m in [0;36m__getattr__[0;34m(name)[0m
[1;32m    344[0m         [0;32mreturn[0m [0m_qchem[0m[0;34m[0m[0;34m[0m[0m
[1;32m    345[0m [0;34m[0m[0m
[0;32m--> 346[0;31m     [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0;34mf"module {__name__} has no attribute {name}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    347[0m [0;34m[0m[0m
[1;32m    348[0m [0;34m[0m[0m

[0;31mAttributeError[0m: module pennylane has no attribute template
AttributeError: module pennylane has no attribute template

